### ISSUE TITLE
Admin API

### ISSUE THREAD

**Issue by Ashab-al** [Ashab-al/telegram-bot_ashab#7]
#3 
Я планирую создать админку внутри бота

Возможности в админе:
1. Категории:
- Получение всех категорий ( get "/api/categories" )
- Создание категории ( post "/api/categories" )
- Редактирование названии категории ( patch "/api/categories" )
- Удаления категории ( delete "/api/categories" )

2. Пользователи:
- Отправка массового сообщения всем активным пользователям (post "api/users/mail_all", params: { text: value(string) })
~ Редактирование кол-во бонусных поинтов у клиента (я введу команду /search @username и бот пришлет его профиль и я смогу редактировать кол-во бонусных поинты) 

- Получить всех пользователей ( get "/api/users" )
- Получить конкретного пользователя ( get "api/users/:id" )
- Редактировать количество бонусов у пользователя ( post "api/users/:id/set_bonus", params: { bonus: NN (integer)} )
- Перевод пользователя в статус works или bot_blocked ( post "api/users/:id/set_status", params: { bot_status: value(string) } )

**Comment by sov-87** [comment]
просмотра списка категорий не планируется в админке?
редактирование - это тоже метод API, почему не указано, что он будет?
в описании было бы хорошо указать и маршруты к методам API

**Comment by sov-87** [comment]
Редактировать количество бонусов у пользователя ( patch "api/users/:id/set_bonus", params: { bonus: NN (integer)} )

Перевод пользователя в статус works или bot_blocked ( patch "api/users/:id/set_status", params: { bot_status: value(string) } )
